"""
Internal tuning constants (not env-configurable).

Change here when profiling; keeps .env limited to keys, URLs, and provider choice.
"""

# --- Extractor / crawl ---
SHALLOW_FETCH_TIMEOUT = 8
EXTRACT_MAX_CHARS = 3000
CRAWL4AI_TIMEOUT = 25
CRAWL4AI_DELAY_BEFORE_HTML = 1.0
CRAWL4AI_PREFER_RAW = False
FETCH_TRY_HTTP_FIRST = False
FETCH_HTTP_MIN_CHARS = 1200
FETCH_SHALLOW_CONCURRENCY = 8
FETCH_DEEP_CONCURRENCY = 2

# --- Agent loop ---
AGENT_MAX_CLAIM_ITERATIONS = 3
AGENT_MAX_QUERY_VARIANTS = 6
AGENT_MAX_REFINE_VARIANTS = 12
AGENT_FETCH_TOP_N = 4
AGENT_PASSAGE_TOP_K = 8
SERP_GATE_MIN_URLS = 15
SERP_GATE_MAX_URLS = 30
AGENT_SNIPPET_FALLBACK_DOCS = 2
SHALLOW_FETCH_SHORT_LIMIT = 8
SHALLOW_FETCH_TARGETED_LIMIT = 12
SHALLOW_FETCH_ITERATIVE_LIMIT = 15
DEEP_FETCH_SHORT_LIMIT = 2
DEEP_FETCH_TARGETED_LIMIT = 3
DEEP_FETCH_ITERATIVE_LIMIT = 4
CHEAP_PASSAGE_LIMIT = 12

# --- Evaluation harness ---
EVAL_CASE_DELAY_SEC = 2.0

# --- Logfire (non-secret; token stays in AppSettings) ---
LOGFIRE_SERVICE_NAME = "self-hosted-search-agent"
LOGFIRE_ENVIRONMENT = "development"
LOGFIRE_SEND_TO_LOGFIRE = "if-token-present"
LOGFIRE_LOCAL = True
LOGFIRE_CONSOLE = False
